- name: Demo
  hosts: all
  tasks:
    - debug:
        msg: "Hello"

- name: Facts
  hosts: localhost
  connection: local
  tasks:
    - name: Print fact
      ansible.builtin.debug:
        msg: “{{ ansible_architecture }}”