- name: Variables
  hosts: localhost
  connection: local
  vars:
    URL: play.google.com
  vars_files:
    - just-vars.yml
  tasks:
    - name: Print a task level variable
      vars:
        URL: task.google.com
      ansible.builtin.debug:
        msg: Var URL - {{ URL }}
    - name: Print a play level variable
      ansible.builtin.debug:
        msg: "{{ URL }}"
    - name: Task Output
      ansible.builtin.shell: ls
      register: out
    - name: Print out
      ansible.builtin.debug:
        msg: “{{ out }}”
  roles:
    - sample

