- name: Filters
  hosts: localhost
  connection: local
  vars:
    URL: https://github.com/PavaniThangellapalli/ansible-topics
  tasks:
    - name: Print all words from URL
      ansible.builtin.debug:
        msg: "{{ URL | split('/') }}"

    - name: Print last word from URL
      ansible.builtin.debug:
        msg: "{{ URL | split('/') | last }}"
