- name: Error Handling
  hosts: localhost
  connection: local
  tasks:
    - name: print
      ansible.builtin.shell: cat /etc/passwd | grep demo
      ignore_errors: true
    - name: Print
      ansible.builtin.shell: ls
      register: out
      ansible.builtin.debug:
        msg: "{{ out }}"